dist: xenial
language: scala

scala:
  - 2.11.12
  - 2.12.8

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

install:
  - pip install --user codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport scalafmtCheck scalafmtSbtCheck test:scalafmtCheck scalastyle &&
    sbt ++$TRAVIS_SCALA_VERSION coverageAggregate &&
    codecov;

  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
